pipeline {
    agent any
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') {
            steps {
                bat 'npm install'
            }
        }
        stage('Test') {
            steps {
                // This runs the built-in test runner for React/Node
                bat 'npm test -- --watchAll=false' 
            }
        }
        stage('Deliver') {
            steps {
                bat 'npm run build'
                echo 'Build completed successfully!'
            }
        }
    }
}