pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                bat 'npm install' // Changed from sh to bat
            }
        }
        stage('Test') {
            steps {
                // Ensure the path to the script is correct after the move
                bat 'jenkins/scripts/test.sh' 
            }
        }
    }
}